name: Add codesandbox link

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codesandbox-comment:
    name: Add codesandbox link comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create CodeSandbox link
        id: create-link
        run: |
          echo "::set-output name=codesandbox-link::https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}"

      - name: Add comment with CodeSandbox link
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `You can check this code at CodeSandbox with the link\n${{ steps.create-link.outputs.codesandbox-link }}`
            })
